from pygame import image, font, init, display, mixer

# inicializando para nao dar erro
init()
display.set_mode((360, 640))

# imagens
bg = image.load("assets/bg.png").convert_alpha()
logo = image.load("assets/logo.png").convert_alpha()
mesa = image.load("assets/mesa.png").convert_alpha()
xic_tras = image.load("assets/xic_tras.png").convert_alpha()
xic_frente = image.load("assets/xic_frente.png").convert_alpha()
colher = image.load("assets/colher.png").convert_alpha()
cara_main = image.load("assets/cara_main.png").convert_alpha()
cara_creditos = image.load("assets/cara_creditos.png").convert_alpha()
cara_1 = image.load("assets/cara_1.png").convert_alpha()
cara_2 = image.load("assets/cara_2.png").convert_alpha()
cara_over = image.load("assets/cara_over.png").convert_alpha()
iniciar = image.load("assets/iniciar.png").convert_alpha()
bcreditos = image.load("assets/bcreditos.png").convert_alpha()
coracao_dead = image.load("assets/coracao_dead.png").convert_alpha()
coracao = image.load("assets/coracao.png").convert_alpha()
game_over = image.load("assets/game_over.png").convert_alpha()
seta_d = image.load("assets/seta_d.png").convert_alpha()
seta_l = image.load("assets/seta_l.png").convert_alpha()
seta_r = image.load("assets/seta_r.png").convert_alpha()
seta_u = image.load("assets/seta_u.png").convert_alpha()
setav_d = image.load("assets/setav_d.png").convert_alpha()
setav_l = image.load("assets/setav_l.png").convert_alpha()
setav_r = image.load("assets/setav_r.png").convert_alpha()
setav_u = image.load("assets/setav_u.png").convert_alpha()
setav_d = image.load("assets/setav_d.png").convert_alpha()
timerbox = image.load("assets/timerbox.png").convert_alpha()
icone = image.load("assets/icone.png").convert_alpha()
iniciar_f = image.load("assets/iniciar_f.png").convert_alpha()
bcreditos_f = image.load("assets/bcreditos_f.png").convert_alpha()
pedro = image.load("assets/pedro.png").convert_alpha()
voltar = image.load("assets/voltar.png").convert_alpha()
voltar_f = image.load("assets/voltar_f.png").convert_alpha()
sair = image.load("assets/sair.png").convert_alpha()
sair_f = image.load("assets/sair_f.png").convert_alpha()
xic_tras_morta = image.load("assets/xic_tras_morta.png").convert_alpha()
xic_frente_morta = image.load("assets/xic_frente_morta.png").convert_alpha()
b_menu = image.load("assets/b_menu.png").convert_alpha()
b_menu_f = image.load("assets/b_menu_f.png").convert_alpha()
denovo = image.load("assets/denovo.png").convert_alpha()
denovo_f = image.load("assets/denovo_f.png").convert_alpha()
highscore_star = image.load("assets/highscore_star.png").convert_alpha()
missed = image.load("assets/missed.png").convert_alpha()
acerto = image.load("assets/acerto.png").convert_alpha()
mini_high = image.load("assets/mini_high.png").convert_alpha()


# fontes
fonte_scoremax = font.Font("assets/fonte.ttf", 22)
fonte_score = font.Font("assets/fonte.ttf", 62)
fonte_creditos = font.Font("assets/fonte.ttf", 20)
fonte_mini_high = font.Font("assets/fonte.ttf", 14)

# musica
som_botao = mixer.Sound("assets/botao.wav")